<?php

/**
 * @file
 * Contains citi_bike.module..
 */
DEFINE('CITI_BIKE_API_BASE_URL', 'https://feeds.citibikenyc.com/stations/stations.json');

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function citi_bike_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the citi_bike module.
    case 'help.page.citi_bike':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds a block for viewing Citi Bike') . '</p>';
      return $output;
    default:
  }
}

/**
 * Implements hook_theme().
 */
function citi_bike_theme($existing, $type, $theme, $path) {
  return array(
    'citi_bike_stations' => [
      'template' => 'citi-bike-stations',
      'variables' => [
        'stations' => NULL,
      ],
    ],
  );
}